spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: admin
        password: 123456789
        url: jdbc:mysql://ddangkong0.c6mujyxzjz4b.ap-northeast-2.rds.amazonaws.com:3306/ddangkong?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true

    thymeleaf:
        enabled: true
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML
