spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1234
        url: jdbc:mysql://localhost:3306/ddangkong

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true

    thymeleaf:
        enabled: true
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML
